env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  jsx-a11y/label-has-associated-control: off  # Turned off due to modern label syntax
settings: 
  import/resolver:
    node:
      moduleDirectory:
        - src
        - node_modules
