"""Course

Revision ID: 02ef6072cd40
Revises: ac5fa7395fad
Create Date: 2022-03-14 17:00:48.088900

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '02ef6072cd40'
down_revision = 'ac5fa7395fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_weight', sa.Float(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coursemajorlink',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'major_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coursemajorlink')
    op.drop_table('course')
    # ### end Alembic commands ###
